// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask;

#nullable disable

namespace TestTask.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230929124858_MG_17")]
    partial class MG_17
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestTask.BodyTable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ACCELERATOR_LINK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARMREST_VISITOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ASH_RECEPTACLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BATTERY_CARRIER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAB_MOUNTING_CAB_MOUNTING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAUTION_PLATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTROL_PANEL_GLOVE_BOX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONVEX_DECORATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Car_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMBLEM_NAME_PLATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLOOR_INSULATOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_BUMPER_BUMPER_STAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_DOOR_LOCK_AND_HANDLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_DOOR_SIDE_GROOVE_GLAZING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_DOOR_VENTILATOR_WINDOW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_FENDER_APRON_DASH_PANEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_FLOOR_PANEL_FRONT_FLOOR_MEMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FUEL_TANK_PIPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOOD_LOCK_HINGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOUSING_PANEL_WINDSCREEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INSIDE_TRIM_BOARD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCK_KIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAT_SILENCER_PAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RADIATOR_GRILLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REAR_BODY_FLOOR_FENDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REAR_BODY_GUARD_FRAME_TRUNK_DOOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REAR_BODY_RETAINER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REAR_BODY_SIDE_PANEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REAR_VENTILATOR_CEILING_VENTILATION_NOZZLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROOF_HEADLINING_SILENCER_PAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROOF_REAR_PANEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEATS_SEAT_TRACK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEAT_BELT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPARE_WHEEL_HOLDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUSPENSION_CROSSMEMBER_LINING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOOL_BOX_LICENSE_PLATE_BRACKET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VISOR_FRONT_FENDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WINDOW_UP_THE_DOOR_DRIVES_HINGE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BodyTables");
                });

            modelBuilder.Entity("TestTask.Car", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("TestTask.CarsTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ATM_MTM")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ATM MTM");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body_1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Body 1");

                    b.Property<string>("Body_2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Body 2");

                    b.Property<string>("Bulding_Condition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Bulding Condition");

                    b.Property<string>("Cab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Car_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complectation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DECK_CAB")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DECK,CAB");

                    b.Property<string>("DECK_MATERIAL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DECK(MATERIAL)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desk")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Desk");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Destination");

                    b.Property<string>("Destination_1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Destination 1");

                    b.Property<string>("Destination_2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Destination 2");

                    b.Property<string>("Drivers_Position")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Drivers Position");

                    b.Property<string>("Emission_Regulation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Emission Regulation");

                    b.Property<string>("Engine_1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Engine 1");

                    b.Property<string>("Engine_2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Engine 2");

                    b.Property<string>("Fuel_Induction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fuel Induction");

                    b.Property<string>("Gear_Shift_Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Gear Shift Type");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loading_Capacity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Loading Capacity");

                    b.Property<string>("Model_Mark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Model Mark");

                    b.Property<string>("NOOF_DOORS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOOF DOORS");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Product");

                    b.Property<string>("ROOF")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROOF");

                    b.Property<string>("Rear_Time")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rear Time");

                    b.Property<string>("Rear_Tire")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rear Tire");

                    b.Property<string>("Roll_Bar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Roll Bar");

                    b.Property<string>("Seating_Capasity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Seating Capasity");

                    b.Property<string>("Side_Window")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Side Window");

                    b.Property<string>("Top_Back_Dorr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Top Back Door");

                    b.Property<string>("Transmission_Model")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Transmission Model");

                    b.Property<string>("Truck_Or_Van")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Truck or Van");

                    b.Property<string>("Vehicle_Model")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Vehicle Model");

                    b.HasKey("Id");

                    b.ToTable("CarsTables");
                });

            modelBuilder.Entity("TestTask.Detail", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("TestTask.ElectricsTable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AIRBAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANALYZER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANTENNA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANTI_LOCK_BRAKE_DEVICES_VSC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ANTI_THEFT_DEVICE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BACK_LIGHT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BATTERY_BATTERY_CABLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLEARANCE_BACK_SONAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Car_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOOR_MOTOR_DOOR_SOLENOID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ELECTRONIC_FUEL_INJECTION_SYSTEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_CLEARANCE_LAMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_TURN_SIGNAL_LAMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLASS_WASHER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEADLIGHTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEATING_AIR_CONDITIONING_COMPRESSOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEATING_AIR_CONDITIONING_CONTROL_DUCT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEATING_AIR_CONDITIONING_COOLER_PIPING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEATING_AIR_CONDITIONING_COOLER_UNIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEATING_AIR_CONDITIONING_HEATER_UNIT_IMPELLER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEATING_AIR_CONDITIONING_SET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEATING_AIR_CONDITIONING_VACUUM_PIPING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HEATING_AIR_CONDITIONING_WATER_PIPING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MIRROR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAVIGATION_SYSTEM_FRONT_MONITORDISPLAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RADIO_RECEIVER_AMPLIFIER_CONDENSER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REAR_LICENSE_PLATE_LAMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REAR_WASHER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REAR_WIPER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPEAKER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TURN_INDICATOR_LIGHT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WINDSCREEN_WIPER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WIRELESS_DOOR_LOCK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WIRING_TERMINAL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ElectricsTables");
                });

            modelBuilder.Entity("TestTask.EngineTable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AIR_CLEANER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAMSHAFT_VALVE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CARBURETOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CARBURETOR_ASSEMBLY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAUTION_PLATE_NAME_PLATE_ENGINE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COLLECTOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRANKSHAFT_PISTONS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CYLINDER_BLOCK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CYLINDER_HEAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Car_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISTRIBUTOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENGINE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENGINE_OIL_COOLER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENGINE_OIL_PUMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EXHAUST_GAS_PIPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EXHAUST_GAS_RECIRCULATION_SYSTEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FUEL_FILTER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FUEL_PUMP_PIPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GASKET_SET_FOR_ENGINE_OVERHAUL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GENERATOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GENERATORSTARTER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IGNITION_COIL_SPARK_PLUG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INJECTION_POWER_SYSTEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INJECTION_PUMP_ASSEMBLY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INJECTION_PUMP_BODY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INSTALLATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOZZLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OIL_FILTER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PARTIAL_ENGINE_ASSEMBLY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RADIATOR_WATER_OUTLET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHORT_ENGINE_ASSEMBLY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STANDARD_TOOLS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STARTER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIMING_COVER_REAR_END_PLATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VACUUM_PIPING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VACUUM_PUMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VENTILATION_HOSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("V_BELT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WATER_PUMP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EngineTables");
                });

            modelBuilder.Entity("TestTask.TransmissionTable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BRAKE_PEDAL_BRACKET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BRAKE_PIPE_TERMINAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLUTCH_HYDRAULIC_SLAVE_CYLINDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLUTCH_MASTER_CYLINDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLUTCH_RELEASE_FORK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Car_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISC_WHEEL_WHEEL_CAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DRIVE_SHAFT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_AXLE_ARM_STEERING_KNIGHT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_AXLE_CASE_DIFFERENTIAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_DRIVE_SHAFT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_SPRING_SHOCK_ABSORBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FRONT_WHEEL_HUB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GEARBOX_SHAFT_CROSS_JOINT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GEAR_SHIFT_FORK_LEVER_SHAFT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GEAR_SHIFT_LEVER_RETAINER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HANDBRAKE_CYLINDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PEDAL_FLEXIBLE_HOSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POWER_STEERING_TUBE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POWER_TAKE_OFF_CASE_GEAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RANGE_LEVER_SHIFT_ROD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REAR_AXLE_CASE_DIFFERENTIAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REAR_DRIVE_SHAFT_HUB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REAR_SPRING_SHOCK_ABSORBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPEEDOMETER_DRIVE_GEAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STEERING_COLUMN_AND_SHAFT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STEERING_WHEEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANSAXLE_OR_TRANSMISSION_ASSY_GASKET_SET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANSFER_ASSEMBLY_GASKET_SET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANSFER_CASE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANSFER_CASE_EXTENSION_HOUSING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANSMISSION_GEAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VANE_PUMP_TANK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WINCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WINCH_KIT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransmissionTables");
                });
#pragma warning restore 612, 618
        }
    }
}
